target 'Persistance' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CTPersistance
  pod "CTMediator"
  pod "HandyFrame"
  pod "SQLCipher"

end
