# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'git@gitlab.91jkys.com:iOS/KangshengPods/KKPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'ReactiveObjc' do
    
    pod 'ReactiveObjC'
 
end
