# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

source 'git@gitlab.91jkys.com:iOS/KangshengPods/KKPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'DDLog' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'CocoaLumberjack', '3.3.0'
 
end
